apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: desire6g-so
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    run: desire6g-so
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: desire6g-so
  name: desire6g-so
spec:
  containers:
  - image: harbor.nbfc.io/desire6g/desire6g-so
    name: desire6g-so
    ports:
    - containerPort: 8000
    resources: {}
    env:
      - name: RABBITMQ_HOST
        value: "rabbitmq"
      - name: SERVICE_NAME
        value: "main"
      - name: FINAL_TOPIC
        value: "input_topic"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
