apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: rabbitmq
spec:
  ports:
  - port: 15672
    protocol: TCP
    targetPort: 15672
    name: port1
  - port: 5672
    protocol: TCP
    targetPort: 5672
    name: port2
  selector:
    run: rabbitmq
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: rabbitmq
  name: rabbitmq
spec:
  containers:
  - image: rabbitmq:management
    name: rabbitmq
    ports:
    - containerPort: 15672
      name: port1
    - containerPort: 5672
      name: port2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
